if(CMAKE_HOST_WIN32)
find_path(ZLG2_INCLUDE_DIR zlgcan.h PATH_SUFFIXES ZLG)
find_library(ZLG2_LIBS NAMES usbcan-* PATH_SUFFIXES MS x64 x86 win32)
elseif(CMAKE_HOST_UNIX)
find_path(ZLG2_INCLUDE_DIR NAMES zlgcan.h PATH_SUFFIXES ZLG)
find_library(ZLG2_LIBS NAMES usbcan-*)
else()
message(FATAL_ERROR "Unsupported OS " ${CMAKE_SYSTEM_NAME})
endif(CMAKE_HOST_WIN32)
if(ZLG2_INCLUDE_DIR AND ZLG2_LIBS)
set(ZLG2_FOUND TRUE)
message(STATUS "Found ZLG2")
else()
unset(ZLG2_FOUND)
unset(ZLG2_INCLUDE_DIR)
unset(ZLG2_LIBS)
if(ZLG2_FIND_REQUIRED)
message(FATAL_ERROR  "Not found ZLG2")
else()
message(WARNING "Not found ZLG2")
endif()
endif()