if(CMAKE_HOST_WIN32)
find_path(Kvaser_INCLUDE_DIR canlib.h PATH_SUFFIXES kvaser)
find_library(Kvaser_LIBS NAMES canlib32 PATH_SUFFIXES MS x64 x86 win32)
elseif(CMAKE_HOST_UNIX)
find_path(Kvaser_INCLUDE_DIR NAMES canlib.h PATH_SUFFIXES kvaser)
find_library(Kvaser_LIBS NAMES canlib)
else()
message(FATAL_ERROR "Unsupported OS " ${CMAKE_SYSTEM_NAME})
endif(CMAKE_HOST_WIN32)
if(Kvaser_INCLUDE_DIR AND Kvaser_LIBS)
set(Kvaser_FOUND TRUE)
message(STATUS "Found Kvaser")
else()
unset(Kvaser_FOUND)
unset(Kvaser_INCLUDE_DIR)
unset(Kvaser_LIBS)
if(Kvaser_FIND_REQUIRED)
message(FATAL_ERROR  "Not found Kvaser")
else()
message(WARNING "Not found Kvaser")
endif()
endif()